[package]
name = "aur"
version = "0.1.0"
authors = ["Axel Navarro <navarroaxel@gmail.com>"]
edition = "2021"

[lib]

[dependencies]
futures = "0.3.31"
reqwest = { version = "0.12.24", features = ["gzip", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
